spring:
  profiles:
    active: local

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

jwt:
  secret: ${JWT_SECRET:your_jwt_secret_key_here_make_it_long_and_secure_at_least_256_bits}
  access-token-validity: 1800000  # 30분
  refresh-token-validity: 604800000  # 7일

logging:
  level:
    root: info
    com.forrrest: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  port: 8081